name: Shell Lint

on:
  push:
    paths:
      - '**.sh'

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.1.0
      - uses: azohra/shell-linter@v0.2.0
        with:
          path: "*.sh"
