name: Shell Lint

on: push
  # push:
  #   paths:
  #     - '**.sh'

jobs:
  lint:
    name: Lint
    timeout-minutes: 3
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.1.0
      - uses: bewuethr/shellcheck-action@v2.0.2
